apiVersion: batch/v1
kind: Job
metadata:
  name: carmely-nn-standard-hps-job-lstm-3
  namespace: user-carmely-reiska
spec:
  backoffLimit: 10
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - name: carmely-nn-standard-hps-container
          image: ccu-k8s.inf.uni-konstanz.de:32250/carmely.reiska/nn-standard-hps:latest
          command: ["/bin/bash"]
          args:
            - -c
            - >
              set -euxo pipefail &&
              export POD_ID=${RUN_ID##*-} &&
              mkdir -p /abyss/home/results/lstm/$POD_ID &&
              cd /abyss/home/nn_standard_architecture_hps &&
              mkdir -p results &&
              if [ ! -d results/LSTM ]; then cp -r /abyss/home/nn_standard_architecture_hps/results/LSTM results/LSTM; fi &&
              python train_lstm.py --configs 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100 &&
              echo "Contents of results/LSTM:" &&
              ls -lh results/LSTM/ &&
              cp -vr results/LSTM/* /abyss/home/results/lstm/$POD_ID/ &&
              echo "Copied files to /abyss/home/results/lstm/$POD_ID:" &&
              ls -lh /abyss/home/results/lstm/$POD_ID/
          env:
            - name: RUN_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "40Gi"
              cpu: "4"
              nvidia.com/gpu: "1"
            limits:
              memory: "40Gi"
              cpu: "8"
              nvidia.com/gpu: "1"
          volumeMounts:
            - mountPath: /abyss/home
              name: cephfs-home
              readOnly: false
            - mountPath: /abyss/shared
              name: cephfs-shared
              readOnly: false
            - mountPath: /abyss/datasets
              name: cephfs-datasets
              readOnly: true
      imagePullSecrets:
        - name: registry-ro-login
      nodeSelector:
        kubernetes.io/hostname: belial
      restartPolicy: Never
      volumes:
        - name: cephfs-home
          hostPath:
            path: /cephfs/abyss/home/carmely-reiska
        - name: cephfs-shared
          hostPath:
            path: /cephfs/abyss/shared
        - name: cephfs-datasets
          hostPath:
            path: /cephfs/abyss/datasets

